version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candidate-api
    command: sh -c "uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candidate-ui
    command: streamlit run webapp/1_Landing.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped